const LAYERS=["Data & Knowledge","Model","Agent & Infrastructure","Application & Workflow","Production & Business"];
const PRIMITIVES=["Compute","Networking","Storage","Security"];
const IMPACTS=["Disruptive","Step-change","Incremental","Packaging / distribution"];
const W={"Disruptive":4,"Step-change":3,"Incremental":1,"Packaging / distribution":.5};
let db,heatView="layers"; const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const fd=d=>new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(d+"T12:00:00Z"));
const score=a=>a.reduce((s,x)=>s+(W[x.impact]||1),0);
const latestFor=l=>[...db.updates].filter(x=>x.layer===l).sort((a,b)=>b.date.localeCompare(a.date))[0];
const topBreakthroughs=(l,n=2)=>[...db.updates].filter(x=>x.layer===l).sort((a,b)=>(W[b.impact]||1)-(W[a.impact]||1)||b.date.localeCompare(a.date)).slice(0,n);
function velocity(){const end=new Date(db.updatedAt),cut=new Date(end);cut.setUTCMonth(cut.getUTCMonth()-36);const raw=Object.fromEntries(LAYERS.map(l=>[l,0]));db.updates.forEach(x=>{const d=new Date(x.date+"T12:00:00Z");if(d<cut)return;const age=(end-d)/(365.25*864e5),r=age<=1?1:age<=2?.65:.35;raw[x.layer]+=(W[x.impact]||1)*r});const max=Math.max(1,...Object.values(raw));return Object.fromEntries(LAYERS.map(l=>[l,Math.round(raw[l]/max*100)]))}
const velLabel=p=>p>=75?"High":p>=45?"Medium":p>0?"Low":"None";
function customerConsequence(x){return x.customerConsequence||x.whyCare}
function renderOverall(){const d=db.overallDirection;$("overallDirectionTitle").textContent=d.title;$("overallDirectionSummary").textContent=d.summary;$("overallDestination").textContent=d.destination;$("overallConstraint").textContent=d.constraint;$("overallSources").innerHTML=d.sources.map(s=>`<a href="${s.url}" target="_blank" rel="noopener">${esc(s.name)} ↗</a>`).join("")}
function renderDirection(){const v=velocity();$("directionBody").innerHTML=db.trajectories.map(t=>`<tr><td><span class="layer-name">${esc(t.layer)}</span><span class="layer-desc">${esc(t.description)}</span></td><td>${esc(t.now)}</td><td>${esc(t.direction)}</td><td>${esc(t.constraint)}</td><td><b>${velLabel(v[t.layer])}</b><div class="velocity-track"><div class="velocity-fill" style="width:${v[t.layer]}%"></div></div><small>${v[t.layer]} relative index</small></td><td><div class="breakthroughs">${topBreakthroughs(t.layer).map(x=>`<button class="breakthrough-link" data-item="${esc(x.id)}">${esc(x.title)}</button>`).join("")}</div></td></tr>`).join("");
$("directionCards").innerHTML=db.trajectories.map(t=>`<article class="direction-card"><div class="direction-card-head"><div><span class="section-tag">${esc(t.layer)}</span><p>${esc(t.description)}</p></div><span class="velocity-badge">${velLabel(v[t.layer])} velocity</span></div><div class="mobile-flow"><div><b>NOW</b><p>${esc(t.now)}</p></div><div class="flow-arrow">↓</div><div><b>DIRECTION HYPOTHESIS</b><p>${esc(t.direction)}</p></div></div><details><summary>Constraints, cloud pressure and evidence</summary><div class="mobile-detail"><b>Main constraint</b><p>${esc(t.constraint)}</p><b>Cloud pressure</b><p>${esc((latestFor(t.layer)?.cloudPrimitives||[]).join(" · "))}</p><b>Evidence</b><div class="breakthroughs">${topBreakthroughs(t.layer,3).map(x=>`<button class="breakthrough-link" data-item="${esc(x.id)}">${esc(x.title)}</button>`).join("")}</div></div></details></article>`).join("")}
function renderLead(){const x=[...db.updates].sort((a,b)=>b.date.localeCompare(a.date))[0];$("leadDate").textContent=fd(x.date);$("leadLayer").textContent=x.layer;$("leadImpact").textContent=x.impact;$("leadTitle").textContent=x.title;$("leadWhy").textContent=x.whyCare;$("leadBefore").textContent=x.before;$("leadAfter").textContent=x.after;$("leadImplication").textContent=x.architectureImplication||x.learn;$("leadCloud").textContent=(x.cloudPrimitives||[]).join(" · ");$("leadTradeoffs").innerHTML=(x.tradeoffs||[]).map(t=>`<span>${esc(t)}</span>`).join("");$("leadCustomer").textContent=customerConsequence(x);$("leadLearn").textContent=x.learn;const s=x.sources?.[0];$("leadSource").href=s?.url||"#";$("leadSource").textContent=s?`${s.name} ↗`:"Source";$("leadSource").target="_blank";$("leadSource").rel="noopener"}
function renderHeatmap(){const years=[2022,2023,2024,2025,2026],cats=heatView==="layers"?LAYERS:PRIMITIVES,items=(y,c)=>db.updates.filter(x=>x.date.startsWith(String(y))&&(heatView==="layers"?x.layer===c:(x.cloudPrimitives||[]).includes(c))),vals=[];years.forEach(y=>cats.forEach(c=>vals.push(score(items(y,c)))));const max=Math.max(1,...vals),cells=[];$("heatmap").style.setProperty("--cols",cats.length);cells.push(`<div class="heat-cell header corner">Year</div>${cats.map(c=>`<div class="heat-cell header">${esc(c)}</div>`).join("")}`);years.forEach(y=>{cells.push(`<div class="heat-cell year">${y}</div>`);cats.forEach(c=>{const a=items(y,c),s=score(a),alpha=s?(.1+.58*s/max):0,attrs=heatView==="layers"?`data-year="${y}" data-layer="${esc(c)}"`:`data-year="${y}" data-primitive="${esc(c)}"`;cells.push(`<button class="heat-cell data" style="background:rgba(57,181,74,${alpha.toFixed(2)})" ${attrs} aria-label="${y}, ${esc(c)}, ${a.length} selected changes"><span class="score">${s?s.toFixed(1):"0"}</span><span class="count">${a.length}</span></button>`)})});$("heatmap").innerHTML=cells.join("");$("yearSummary").innerHTML=years.map(y=>{const r=cats.map(c=>({c,s:score(items(y,c))})).sort((a,b)=>b.s-a.s)[0];return `<div><span>${y}</span><b>${r.s?esc(r.c):"No selected milestone"}</b></div>`}).join("")}
function fillFilters(){[2022,2023,2024,2025,2026].forEach(y=>$("yearFilter").add(new Option(y,y)));LAYERS.forEach(v=>$("layerFilter").add(new Option(v,v)));IMPACTS.forEach(v=>$("impactFilter").add(new Option(v,v)))}
function filtered(){const q=$("searchInput").value.trim().toLowerCase(),y=$("yearFilter").value,l=$("layerFilter").value,i=$("impactFilter").value,k=$("kindFilter").value;return [...db.updates].filter(x=>(!y||x.date.startsWith(y))&&(!l||x.layer===l)&&(!i||x.impact===i)&&(!k||x.kind===k)&&(!q||JSON.stringify(x).toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date))}
function card(x){return `<article class="news-card" id="item-${esc(x.id)}"><div class="news-meta"><span>${x.kind==="milestone"?"Milestone":"Signal"}</span><span>${fd(x.date)}</span><span>${esc(x.layer)}</span><span>${esc(x.impact)}</span></div><h3>${esc(x.title)}</h3><p class="news-summary">${esc(x.whyCare)}</p><div class="quick-lens"><span>Cloud: ${esc((x.cloudPrimitives||[]).join(" · "))}</span><span>Trade-offs: ${esc((x.tradeoffs||[]).join(" · "))}</span></div><details><summary>Full architecture analysis</summary><div class="detail-body"><div class="detail-section"><b>WHAT CHANGED</b><p>${esc(x.whatChanged)}</p></div><div class="detail-before-after"><div><b>BEFORE</b><p>${esc(x.before)}</p></div><div><b>AFTER</b><p>${esc(x.after)}</p></div></div><div class="detail-section"><b>ARCHITECTURE IMPLICATION</b><p>${esc(x.architectureImplication||x.learn)}</p></div><div class="detail-section"><b>CLOUD PRIMITIVES</b><p>${esc((x.cloudPrimitives||[]).join(" · "))}</p></div><div class="detail-section"><b>TRADE-OFFS AFFECTED</b><div class="tradeoff-row">${(x.tradeoffs||[]).map(t=>`<span>${esc(t)}</span>`).join("")}</div></div><div class="detail-section"><b>CUSTOMER CONSEQUENCE</b><p>${esc(customerConsequence(x))}</p></div><div class="detail-section"><b>WHAT TO LEARN</b><p>${esc(x.learn)}</p></div><div class="detail-section"><b>EVIDENCE</b><p class="evidence-note">Fact source below. Layer, impact, implication and trade-offs are editorial classifications.</p><ul class="source-list">${(x.sources||[]).map(s=>`<li><a href="${s.url}" target="_blank" rel="noopener">${esc(s.name)} ↗</a></li>`).join("")}</ul></div></div></details></article>`}
function renderArchive(){const a=filtered();$("resultCount").textContent=`${a.length} items`;$("newsGrid").innerHTML=a.length?a.map(card).join(""):'<div class="empty">No items match these filters.</div>'}
function renderReference(){$("layerDefs").innerHTML=db.mentalModel.layers.map(x=>`<div class="definition"><h4>${esc(x.name)}</h4><p>${esc(x.description)}</p></div>`).join("");$("primitiveDefs").innerHTML=db.mentalModel.primitives.map(x=>`<div class="definition"><h4>${esc(x.name)}</h4><p>${esc(x.description)}</p></div>`).join("")}
function goItem(id){$("filterForm").reset();renderArchive();setTimeout(()=>$("item-"+id)?.scrollIntoView({behavior:"smooth",block:"start"}),20)}
function apply({year="",layer="",primitive=""}){$("filterForm").reset();$("yearFilter").value=String(year||"");$("layerFilter").value=layer||"";if(primitive)$("searchInput").value=primitive;renderArchive();$("radar").scrollIntoView({behavior:"smooth",block:"start"})}
function wire(){$("filterForm").addEventListener("submit",e=>{e.preventDefault();renderArchive()});$("resetFilters").onclick=()=>{$("filterForm").reset();renderArchive()};document.addEventListener("click",e=>{const tab=e.target.closest("[data-heat-view]");if(tab){heatView=tab.dataset.heatView;document.querySelectorAll("[data-heat-view]").forEach(x=>x.classList.toggle("active",x===tab));renderHeatmap();return}const t=e.target.closest("[data-item],[data-year]");if(!t)return;if(t.dataset.item)return goItem(t.dataset.item);apply({year:t.dataset.year,layer:t.dataset.layer,primitive:t.dataset.primitive})});const sections=["direction","evolution","radar","reference"].map($);const obs=new IntersectionObserver(es=>es.forEach(en=>{if(en.isIntersecting)document.querySelectorAll(".nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+en.target.id))}),{rootMargin:"-30% 0px -60% 0px"});sections.forEach(s=>obs.observe(s))}
async function init(){const r=await fetch("./updates.json?ts="+Date.now(),{cache:"no-store"});db=await r.json();$("updatedAt").textContent=`Last update ${fd(db.updatedAt.slice(0,10))}`;$("liveCount").textContent=`${db.updates.length} tracked changes`;fillFilters();renderOverall();renderDirection();renderHeatmap();renderLead();renderArchive();renderReference();wire()}
init().catch(e=>{document.body.insertAdjacentHTML("beforeend",`<div class="empty">Could not load data: ${esc(e.message)}</div>`);console.error(e)});